### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by GraphicsHunter** [JimmySuen/integral-human-pose#11]
Hi, could you please add code where inference is done on image/video/webcam? what is the output rate or this model?

**Comment by MetaDev** [comment]
I am also trying inference, but I can't unrar the downloaded models. any help there?

**Comment by lck1201** [comment]
@tianfanzhu  @MetaDev  You can simply modify test.py and net_modules.py to do inference, there isn't anything new.

**Comment by lck1201** [comment]
Now close this issue, I would re-open it if new questions come out.

**Comment by MetaDev** [comment]
I can get output from the model but now I am looking to postprocess the output into 3D joints. Where could I find the code for that. I would like to make visualisation like in the top of the readme (image->3D in matplotlib). Thanks!

**Comment by MetaDev** [comment]
I figured it out. I had to use the "result_func" and "debug_vis_patch", the code is pretty clear.

**Comment by lck1201** [comment]
Good to know you have solve it!

**Comment by wangm-word** [comment]
> I figured it out. I had to use the "result_func" and "debug_vis_patch", the code is pretty clear.

can you tell me how to inference a img?>
