### ISSUE TITLE
Code for 2d pose

### ISSUE THREAD

**Issue by meijieru** [JimmySuen/integral-human-pose#12]
Could you please share the code for 2d pose detection for reproducing the experiment in the paper?

**Comment by lck1201** [comment]
@meijieru  Hi, please refer to [here](https://github.com/leoxiaobin/human-pose-estimation.pytorch) , our implementation is quite similar with this project.

**Comment by lck1201** [comment]
Now close this issue, I would re-open it if new questions come out.
