### ISSUE TITLE
camera parameters

### ISSUE THREAD

**Issue by XiumeiChen** [JimmySuen/integral-human-pose#13]
Hi, thanks for sharing.
Could you tell me how did you calculate the camera parameters, such as fl and c_p?

**Comment by lck1201** [comment]
@XiumeiChen  Hi, for original integral pose regression, we use the camera parameters provided by HM3.6M. For ECCV challenge, we project & back-project between 3D and 2D based on weak perspective.

**Comment by XiumeiChen** [comment]
@lck1201 thank you. But I still have difficult with getting the camera params using H3.6m official tool. Does fl means the focal length, i.e. obj.f in H36MCamera.m, and obj.k for c_p?

**Comment by lck1201** [comment]
@XiumeiChen  Yes, fl = focal length. And what do you mean obj.f, obj.k? Could you post some samples?

**Comment by XiumeiChen** [comment]
@lck1201 I'm confused with getting fl and c_p using the official tool of H3.6m. It seems the camera params are in the class "H36MCamera.m", then which params stand for fl and c_p?
![image](https://user-images.githubusercontent.com/44281274/50418921-0a5d8480-0869-11e9-90d1-b35bc25eeff5.png)

**Comment by lck1201** [comment]
@XiumeiChen  It's clear obj.f = focal length= fl, and obj.c = center = c_p.  Please refer to [wiki](https://en.wikipedia.org/wiki/Camera_resectioning) for more camera parameter knowledge.

**Comment by XiumeiChen** [comment]
Thank you.
