### ISSUE TITLE
Error testing on COCO

### ISSUE THREAD

**Issue by Godatplay** [JimmySuen/integral-human-pose#14]
I'm getting errors while trying to test on the COCO dataset. In order to attempt this, so far I've created a custom config with my paths to the data, added importing coco to all_dataset.py, added coco_Dataset to loader.py (using same template as hm36_Dataset), and am importing coco_Dataset in the test.py found in integral_human_pose. When I try to run that test script, I get this error:
`size mismatch for module.head.features.9.bias: copying a param of torch.Size([1224]) from checkpoint, where the shape is torch.Size([1296]) in current model.`
(and one for weights with the same length mismatch)
Do I have the wrong version of the COCO dataset? I currently have val2017 and annotations.

**Comment by lck1201** [comment]
@Godatplay  Hi, the problem shall in your config file. You build a different network using different network configs. Please check the config.train.patch_height, config.train.patch_width, and network. Refer to  [here](https://github.com/JimmySuen/integral-human-pose/blob/master/pytorch_projects/integral_human_pose/experiments/hm36/resnet50v1_ft/d-mh_ps-256_deconv256x3_min-int-l1_adam_bs32-4gpus_x300-270-290/lr1e-3.yaml)

**Comment by lck1201** [comment]
Close issue, re-open if you have further questions
