### ISSUE TITLE
请问运行速度怎么样？

### ISSUE THREAD

**Issue by lunalulu** [JimmySuen/integral-human-pose#19]
请问积分姿态估计对2D姿态估计的速度如何？能否在嵌入式端达到实时？
谢谢回复~

**Comment by lck1201** [comment]
Hi @lunalulu , the time consumption depends on platform/GPU/underlying optimization....etc. You'd better try on your own and share with us.

**Comment by lck1201** [comment]
Close issue, re-open if you have further questions

**Comment by lunalulu** [comment]
thanks for your reply
