### ISSUE TITLE
COCO DataLoader

### ISSUE THREAD

**Issue by Naman-ntc** [JimmySuen/integral-human-pose#2]
Hi, Thanks For Uploading the code. I couldn't find dataloader for COCO dataset (_single person_) in this repository. It would be very helpful if you could share dataloader for coco dataset as well or point me to a source from where you used coco dataloader.
I want to work on coco dataloader and for standardization it would be really great to use dataloader used by this work!!

Thanks

**Comment by lck1201** [comment]
@Naman-ntc  Hi, code has been updated, plz check

**Comment by Naman-ntc** [comment]
Thankss for quick response! :D
Closing this
