### ISSUE TITLE
Adding other datasets and different backbones

### ISSUE THREAD

**Issue by MetaDev** [JimmySuen/integral-human-pose#21]
I would like to add some stuff this repository:
-extra datasets (such as LSP for 2D)
-backbones (such as Resnet18)
-different joint set, omitting the nose
Any suggestions on where in the code I can best start on this? Thanks.

**Comment by lck1201** [comment]
@MetaDev  Hi,
- extra datasets: refer to _pytorch_projects/common_pytorch/dataset_  , you need to parse the dataset yourself.
- backbones: see _pytorch_peojects/common_pytorch/blocks/resnet_pose.py_ to understand how we configure the network
- difference joint set: Omit nose in dataset parsing / training/ testing? Please be more specific.
 I hope these suggestions could help you.

**Comment by lck1201** [comment]
Close issue, re-open if you have further questions
