### ISSUE TITLE
Hi, what is e_jt_pck and e_pck in evaluation code?

### ISSUE THREAD

**Issue by mks0601** [JimmySuen/integral-human-pose#22]
Hi, can you tell me what are `e_jt_pck` and `e_pck` in `pytorch_projects/common_pytorch/dataset/hm36.py`?
Also, what are `t_start`, `t_end`, and `t_step` in the same code? They are in the evaluation function, but I cannot figure out what they mean. Thank you in advance.

**Comment by mks0601** [comment]
And why are you using `abs` to calculate final error in the evaluation function? I think l2 norm is correct as in the paper http://vision.imar.ro/human3.6m/pami-h36m.pdf

**Comment by lck1201** [comment]
@mks0601  Hi,  I only see that ```abs``` is used for caclucate x/y/z error separately in hm36.py. And for ```e_jt_pck``` & ```e_pck```, in fact, they are legacy codes used for other eval metrics, and now useless in evaluation.

**Comment by mks0601** [comment]
Thanks.
