### ISSUE TITLE
How are the images cropped?

### ISSUE THREAD

**Issue by isarandi** [JimmySuen/integral-human-pose#27]
Hi,

Thanks for sharing your code! I'm trying to understand how you perform image cropping on Human3.6M. As far as I understand the cropping box is obtained by first taking a 2 meter by 2 meter square parallel to the image plane at the depth of the root joint and projecting this onto the image. Is it done like this?

Thanks!

**Comment by lck1201** [comment]
@isarandi  Yes, exactly.

**Comment by lck1201** [comment]
close issue
