### ISSUE TITLE
Reimplementation of Integral Human Pose

### ISSUE THREAD

**Issue by mkocabas** [JimmySuen/integral-human-pose#29]
Hi @lck1201 and @JimmySuen,

I reimplemented your work for our CVPR19 paper. Maybe you can add it to the readme as. Link: https://github.com/mkocabas/EpipolarPose

It is compatible with PyTorch 1.0, and the H36M results are similar to the paper results.

Thanks!

**Comment by lck1201** [comment]
@mkocabas  Hi, thanks for your work! I will add it soon.
