### ISSUE TITLE
Can you share download link of dataset of ECCV 2018 challenge?

### ISSUE THREAD

**Issue by sjtuytc** [JimmySuen/integral-human-pose#3]
I can't get access to ECCV 2018 challenge because a long delay of the varication in the official Human 2.6m website.
Note that it's not easy to organize dataset like yours,  which may reduce the probable effectiveness of your excellent job, can you provide your handling codes?

**Comment by lck1201** [comment]
@sjtuytc Hi, we download data from official dataset http://vision.imar.ro/human3.6m/description.php, maybe verification will take sometime, please be patient.
