### ISSUE TITLE
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'

### ISSUE THREAD

**Issue by sjtuytc** [JimmySuen/integral-human-pose#4]
How do I fix this error?
It occurs at common_pytorch/common_loss/integral.py Line17

**Comment by lck1201** [comment]
@sjtuytc  Hi, the code runs properly on our machine. Please check you have installed everything correctly.

**Comment by xiangdonglai** [comment]
@lck1201  Hello. I also encounter this problem. May I know the PyTorch version that you use?

**Comment by lck1201** [comment]
@xiangdonglai  I install via _conda install pytorch torchvision -c pytorch_, version 0.4.0

**Comment by xiangdonglai** [comment]
@lck1201 Thank you for your response. I also solve the problem using **Python 3.6** and **PyTorch 0.4.0**.

**Comment by lck1201** [comment]
@sjtuytc  please follow @xiangdonglai  to install requirements. 
Now close issue.. If you have further question, I would re-open it.
