### ISSUE TITLE
I1 or I2 loss

### ISSUE THREAD

**Issue by mks0601** [JimmySuen/integral-human-pose#7]
Hi, thanks for sharing nice work.
It seems only I* loss is used in this code. Can you share code for I1 or I2 loss?

**Comment by lck1201** [comment]
@mks0601 Hi, maybe we will release the code in the future, but recently we don't have the plan.

**Comment by strawberryfg** [comment]
@mks0601 Check [this](https://github.com/strawberryfg/int-3dhuman-I1)

**Comment by lck1201** [comment]
Now close this issue, I would re-open it if new questions come out.
